DATA_PREPROCESSING_BASELINE_PLAN = (
    "BASELINE PLAN FOR DATA PREPROCESSING TASK\n"
    "1. DATA QUALITY CHECK\n"
    " - Count missing values\n"
    " - Identify duplicates\n"
    " - Detect outliers\n"
    " - Check data consistency\n"
    "\n"
    "2. HANDLING MISSING DATA\n"
    " - Delete rows (if appropriate)\n"
    " - Impute values (mean/median/mode)\n"
    " - Use advanced imputation (KNN, regression)\n"
    " - Create missing indicators\n"
    "\n"
    "3. OUTLIER TREATMENT\n"
    " - Remove clear errors\n"
    " - Cap extreme values\n"
    " - Transform skewed distributions\n"
    " - Apply domain-specific rules\n"
    "\n"
    "4. DATA TRANSFORMATION\n"
    " - Encode categorical variables\n"
    " - Scale numerical features\n"
    " - Normalize skewed distributions\n"
    " - Extract datetime components\n"
    " - Process text data\n"
    " - Handle cyclical features\n"
    "\n"
    "5. FEATURE CREATION\n"
    " - Generate interaction terms\n"
    " - Create domain-specific features\n"
    " - Calculate aggregations\n"
    " - Derive new metrics\n"
    "\n"
    "6. DIMENSIONALITY REDUCTION\n"
    " - Remove low variance features\n"
    " - Eliminate highly correlated features\n"
    " - Apply PCA/SVD if needed\n"
    " - Use feature importance for selection\n"
    "\n"
    "## IMPORTANT INSTRUCTIONS\n"
    "- For derifed feature group creation requests, suggest to engineer new features\n"
)

FEATURE_GROUP_CREATION_BASELINE_PLAN = (
    "BASELINE PLAN FOR FEATURE GROUP CREATION TASK\n"
    "1. DATASET SPLITTING DECISION\n"
    " - Analyze if dataset should be split into multiple feature groups\n"
    " - Consider entity relationships (users, products, transactions)\n"
    " - Evaluate feature update frequencies (real-time vs batch)\n"
    " - Check for distinct feature categories (behavioral, demographic)\n"
    " - Determine if splitting would improve organization or performance\n"
    "\n"
    "2. FEATURE GROUP DEFINITION\n"
    " - Name each feature group meaningfully (use descriptive names like 'customer_demographics', 'sales_transactions')\n"
    " - IMPORTANT: Always mention the exact feature group name(s) in your plan\n"
    " - Select features for each group\n"
    " - Provide clear description of contents\n"
    " - Define appropriate version (start with 1)\n"
    "\n"
    "3. PRIMARY KEY SELECTION\n"
    " - Identify unique identifier column(s)\n"
    " - Ensure primary key uniquely identifies each row\n"
    " - Consider composite keys if needed\n"
    " - Verify primary key data quality (no nulls, no duplicates)\n"
    "\n"
    "4. ONLINE SERVING CONFIGURATION\n"
    " - Determine if online serving is needed\n"
    " - Set online_enabled=True for real-time serving requirements\n"
    " - Consider serving latency requirements\n"
    " - Evaluate feature freshness needs\n"
    "\n"
    "5. TIME DIMENSION CONFIGURATION\n"
    " - Identify timestamp or date columns\n"
    " - Set event_time parameter ONLY if valid time columns exist\n"
    " - Consider time-travel requirements\n"
    " - Determine if point-in-time correctness is needed\n"
    "\n"
    "6. PARTITIONING STRATEGY\n"
    " - Assess if partitioning is needed (for large datasets)\n"
    " - Identify appropriate partition_key column(s)\n"
    " - Consider data distribution across partitions\n"
    " - Set partition_key parameter ONLY if needed\n"
    "\n"
    "7. FEATURE DOCUMENTATION\n"
    " - Create descriptions for each feature group\n"
    " - Document every feature with clear descriptions\n"
    " - Include data types and valid ranges\n"
    " - Note business significance of each feature\n"
    "\n"
    "## IMPORTANT INSTRUCTIONS"
    "- Be sure in your proposal, because it is a final step to create a feature group,"
    " so you must clearly say whether feature group will be online or offline, what primary key, what features included, etc, so the user can understand the plan\n"
    "- Don't include the version in the feature group name. BAD: titanic_passenger_features_v1, GOOD: titanic_passenger_features\n"
)

NEXT_STEPS_BASELINE_PLAN = (
    "SPECIAL BASELINE PLAN: NEXT STEP SUGGESTION (NOT detailed workflow planning)\n"
    "\n"
    "## WORKFLOW_PLAN FIELD INSTRUCTIONS:\n"
    "CRITICAL: For the workflow_plan field, do NOT create numbered step-by-step procedures.\n"
    "Instead, provide only a simple recommendation and approval question:\n"
    "\n"
    "**After DATA ANALYSIS with data quality issues:**\n"
    "Based on the analysis findings, I recommend proceeding with data preparation to address the missing values and outliers. Do you want to proceed with data preparation?\n"
    "\n"
    "**After DATA ANALYSIS with clean data:**\n"
    "Your data looks good! You can proceed directly to feature group creation or do data preparation for feature engineering. What would you prefer?\n"
    "\n"
    "**After FEATURE GROUP ANALYSIS:**\n"
    "Based on the feature group analysis, I recommend data preparation to create derived features. Do you want to proceed with data preparation?\n"
    "\n"
    "**After DATA PREPARATION:**\n"
    "Data preparation is complete. Do you want to proceed with feature group creation?\n"
    "\n"
    "**After FEATURE GROUP CREATION:**\n"
    "What would you like to do next? You can create charts, create derived feature groups, or work with other datasets.\n"
    "\n"
    "**After CHART GENERATION:**\n"
    "Would you like to create additional charts or explore other visualization options?\n"
    "\n"
    "## IMPORTANT:\n"
    "- STRICT SEPARATION: introduction field = completion summary, workflow_plan field = next step question ONLY\n"
    "- In introduction field: Summarize what was accomplished, include technical details, end with completion statement\n"
    "- In workflow_plan field: Ask ONE simple next step question without repeating completion information\n"
    "- NEVER repeat the same information in both fields\n"
    "- NEVER include phrases like 'created successfully' in workflow_plan if already mentioned in introduction\n"
    "- NO numbered lists in workflow_plan field for this baseline plan\n"
    "- Base your recommendation on the actual context findings\n"
)

BASELINE_PLANS = {
    "data_preprocessing": DATA_PREPROCESSING_BASELINE_PLAN,
    "feature_group_creation": FEATURE_GROUP_CREATION_BASELINE_PLAN,
    "next_steps": NEXT_STEPS_BASELINE_PLAN,
}
